### ISSUE TITLE
Write a list of known software and SaaS requirements for the prototype

### ISSUE THREAD

**Issue by charlie-moffett** [charlie-moffett/govisland-chatbot#3]

**Comment by gauravcusp** [comment]
Methodology:
Create a Lambda function that enables interaction between the database and the API Gateway. The API gateway would help us create a JSON file that will be used by FB messenger platform via api requests.

Tasks:
- Setup database on AWS
- Write Lambda script to enable the interaction

**Comment by gauravcusp** [comment]
For better understanding, I created this diagram.

![image](https://user-images.githubusercontent.com/31963299/35400478-e7ce9d24-01c4-11e8-9be4-5419115c95c6.png)

**Comment by ishacusp** [comment]
Use a built-in fb messenger chatbot platform - Chatfuel/ManyChat/Others and connect the bot to      AWS Lambda (https://zapier.com/apps/integrations).

**Comment by ishacusp** [comment]
Train the bot by integrating the platform (Chatfuel) with api.ai/wit.ai https://community.chatfuel.com/t/easily-connecting-api-ai-to-chatfuel/3084

**Comment by charlie-moffett** [comment]
Is there anything additional (platforms, plug-ins) we need for gathering location information from Messenger? If it's straightforward then that's great, otherwise I can make separate issue for scoping out that part of the functionality.

**Comment by ishacusp** [comment]
It is doable with the platform itself - https://community.chatfuel.com/t/how-to-get-user-location/830

**Comment by gauravcusp** [comment]
Chatfuel and AWS it is. (Potentially wit.ai for NLP)
